### ISSUE TITLE
status bar stays on screen after using ConsoleWithProgress

### ISSUE THREAD

**Issue by amm042** [parsiad/lazy-table#2]
If you stream a table with ConsoleWithProgress, it works great. But I have more output to display after the table but the 100% progress bar is stuck somehow on the bottom of the screen.

# example
lazy_table.stream(...artist=lazy_table.artists.ConsoleWithProgress())
print("Hello world!")  # this line will be above the status bar.

I think after the table is printed the cursor is positioned before the status bar and it inserts any additional output before the status bar. 

Is there a way to remove the status bar when complete?

**Comment by parsiad** [comment]
Hi @amm042,

Thank you for flagging this. PR #3 should fix this. While I have tested it on my own machine, could you try it out before I merge and let me know if it covers your use cases?

Thanks,
Par

**Comment by amm042** [comment]
yes, looks good. thanks!
